"""Local book corpus construction and inspection APIs."""
from .corpus import (
    build_corpus, get_corpus_status, inspect_book, inspect_book_blocks,
    list_books, load_book_image, load_corpus_snapshot,
)
from .models import (
    Book,
    BookImage,
    BookInspection,
    BookNotFoundError,
    BookParseError,
    BookSummary,
    BuildResult,
    Chapter,
    Chunk,
    CORPUS_VERSION,
    CorpusBuildError,
    CorpusReadError,
    CorpusStatus,
    CorpusChunkRecord,
    CorpusSnapshot,
    KnowledgeError,
    Paragraph,
    SCHEMA_VERSION,
)
from .index import (
    Embedder,
    IndexBuildResult,
    IndexStatus,
    KnowledgeCitation,
    KnowledgeIndexBuildError,
    KnowledgePassage,
    KnowledgeRetriever,
    KnowledgeSearchResult,
    KnowledgeUnavailableError,
    LanceDBKnowledgeRetriever,
    QwenEmbedder,
    build_index,
    get_index_status,
)

__all__ = [
    "Book",
    "BookImage",
    "BookInspection",
    "BookNotFoundError",
    "BookParseError",
    "BookSummary",
    "BuildResult",
    "CORPUS_VERSION",
    "Chapter",
    "Chunk",
    "CorpusBuildError",
    "CorpusReadError",
    "CorpusStatus",
    "CorpusChunkRecord",
    "CorpusSnapshot",
    "KnowledgeError",
    "Paragraph",
    "SCHEMA_VERSION",
    "build_corpus",
    "get_corpus_status",
    "inspect_book",
    "inspect_book_blocks",
    "load_book_image",
    "list_books",
    "load_corpus_snapshot",
    "Embedder",
    "IndexBuildResult",
    "IndexStatus",
    "KnowledgeCitation",
    "KnowledgeIndexBuildError",
    "KnowledgePassage",
    "KnowledgeRetriever",
    "KnowledgeSearchResult",
    "KnowledgeUnavailableError",
    "LanceDBKnowledgeRetriever",
    "QwenEmbedder",
    "build_index",
    "get_index_status",
]
